apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo "Hello Kubernetes!"; sleep 5; done
    image: busybox:latest
    name: hello
