apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginxdemos/hello:plain-text
    ports:
    - name: web
      containerPort: 80
