apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginxdemos/hello:latest
        ports:
        - name: web
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: web
        livenessProbe:
          httpGet:
            path: /
            port: web
